CREATE TABLE `inventory_items` (
  `id` VARCHAR(191) NOT NULL,
  `item_code` VARCHAR(50) NOT NULL,
  `barcode_number` VARCHAR(50) NOT NULL,
  `barcode_type` VARCHAR(20) NOT NULL DEFAULT 'Code128',
  `item_name` VARCHAR(191) NOT NULL,
  `item_name_kn` VARCHAR(191) NULL,
  `main_category` VARCHAR(191) NULL,
  `sub_category` VARCHAR(191) NULL,
  `company_name` VARCHAR(191) NULL,
  `packing` VARCHAR(191) NULL,
  `size` VARCHAR(191) NULL,
  `unit` VARCHAR(191) NULL,
  `hsn_code` VARCHAR(191) NULL,
  `opening_stock` DECIMAL(65,30) NOT NULL DEFAULT 0,
  `current_stock` DECIMAL(65,30) NOT NULL DEFAULT 0,
  `purchase_price` DECIMAL(65,30) NOT NULL DEFAULT 0,
  `cost_price` DECIMAL(65,30) NOT NULL DEFAULT 0,
  `selling_price` DECIMAL(65,30) NOT NULL DEFAULT 0,
  `dealer_price` DECIMAL(65,30) NOT NULL DEFAULT 0,
  `mrp` DECIMAL(65,30) NOT NULL DEFAULT 0,
  `discount_percent` DECIMAL(65,30) NOT NULL DEFAULT 0,
  `gst_percent` DECIMAL(65,30) NOT NULL DEFAULT 0,
  `rack_location` VARCHAR(191) NULL,
  `minimum_stock` DECIMAL(65,30) NOT NULL DEFAULT 0,
  `reorder_quantity` DECIMAL(65,30) NOT NULL DEFAULT 0,
  `sales_account` VARCHAR(191) NULL,
  `purchase_account` VARCHAR(191) NULL,
  `label_width` DECIMAL(65,30) NOT NULL DEFAULT 50,
  `label_height` DECIMAL(65,30) NOT NULL DEFAULT 25,
  `print_count` INTEGER NOT NULL DEFAULT 0,
  `last_printed` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `inventory_items_item_code_key`(`item_code`),
  UNIQUE INDEX `inventory_items_barcode_number_key`(`barcode_number`),
  INDEX `inventory_items_item_name_idx`(`item_name`),
  INDEX `inventory_items_main_category_idx`(`main_category`),
  INDEX `inventory_items_company_name_idx`(`company_name`)
);
